### ISSUE TITLE
[Bug] Signin page flickering

### ISSUE THREAD

**Issue by Pugialli** [creativetimofficial/ct-nextjs-material-dashboard-pro#22]
### Version
2.0.0
### Reproduction link
https://demos.creative-tim.com/nextjs-material-dashboard-pro/authentication/sign-in/basic
### Operating System
Windows
### Device
Laptop
### Browser & Version
Chrome 100.0.4896.88
### Steps to reproduce
1. Go to signin page
2. Pass the mouse around the navbar

---------------------------------------------------
I also removed the cascate on the navbar and the same bug happend eache time I typed on the field for the form. This happended until I removed the footer
### What is expected?
The screen to stay the same
### What is actually happening?
The screen moves left to right and the scrollbar appears.

---
### Solution
Don't know
### Additional comments
Great dashboard!

**Comment by sajadevo** [comment]
**Hi @Pugialli**

Thanks for using our product, could you please provide a video related to this issue since I'm checking it and there is no scroll.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by Pugialli** [comment]
Here is the video showing this issue.

https://user-images.githubusercontent.com/5952940/164720621-19857872-87fc-44c8-9347-0b0bb6c88faf.mp4

Regards,

**Comment by sajadevo** [comment]
**Hi @Pugialli**

Thanks for reporting that we will fix it on the next update of the product.

**Note: To get the latest updates and supports for the products and other related things to Creative Tim please join our [Discord Community](https://discord.gg/7xzMRsRebr).**

**All the best,
Sajad 
React Developer @ [Creative-Tim.com](http://creative-tim.com/)**

**Comment by Pugialli** [comment]
Hello guys,

Any news on that?

**Comment by sajadevo** [comment]
Hi @Pugialli,

Until we didn't release any new update.

Regards,
Sajad
